### ISSUE TITLE
Der oder-Operator der Suche funktioniert nicht

### ISSUE THREAD

**Issue by mYnDstrEAm** [mopsalarm/pr0gramm-tags#1]
`|` oder `or` als Suchoperator scheint nicht (mehr?) zu funktionieren. Das Readme muss entsprechend angepasst werden.

**Comment by mopsalarm** [comment]
Doch tut er. Kannst du ein Beispiel nennen wo es nicht funktioniert?

**Comment by mYnDstrEAm** [comment]
Es funktioniert weder in der App noch auf der normalen Website. Zum Beispiel `wallpaper | papier`. Scheint irgendwie als und-Operator zu fungieren.

**Comment by mopsalarm** [comment]
Hast du das '?' davor vergessen?

**Comment by mYnDstrEAm** [comment]
Tatsächlich. Sorry. Der und Operator funktionierte auch ohne das Fragezeichen. Kannst du im Readme eventuell noch erwähnen, dass man bei der App nichts bzgl Userscript installieren/ändern muss oder über "Erweitert" direkt auf den Abschnitt Syntax verlinken und die Info bzgl vorgestelltem Fragezeichen dort reinverschieben? Und hat das offizielle pr0 noch keinen Oder-Suchoperator oder wie ist das?

**Comment by mopsalarm** [comment]
Der und Operator funktioniert auch nicht ohne das Fragezeichen. Ohne das Fragezeichen wird die erweiterte Suche einfach nicht gerendert, und die normale Suche ignoriert Sonderzeichen einfach. Das ganze ist nicht im pr0gramm, da das ein extra "Drittanbieter"-Service von mir ist.
